{% set name = "py-bip39-bindings" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/polkascan/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 07178c2ef7c4284e1531d344b9a5353dd35a259c20b71276e450d3ab82db2682
  #patches:
  #  - fix-Cargo-pep621.patch
  #  - fix-pyproject-pep621.patch

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . -vvv
  # Compilation fails on windows due to missing __imp__PyObject_NextNotImplemented symbol
  skip: true  # [win and py>=313]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - maturin =0.14.17
    - pip
    - python
    - setuptools-rust
  run:
    - python

test:
  source_files:
    - tests.py
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - pytest -v tests.py
  downstreams:
    - py-sr25519-bindings
    - py-ed25519-zebra-bindings

about:
  home: https://github.com/polkascan/py-bip39-bindings
  summary: 'Python bindings for the tiny-bip39 library: https://crates.io/crates/tiny-bip39'
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - arjanz
    - MementoRC
